// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MusicToCodeBy
{
    internal sealed partial class Vsix
    {
        public const string Id = "MusicToCodeBy.bcef8857-0a66-4bb6-b34f-5c2ac692b10a";
        public const string Name = "Music To Code By";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
