// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MusicToCodeBy
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "43ce9aba-807e-49a7-8de3-f2ba6d484d37";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string CommandSetString = "c61f2690-2d5a-4750-b83e-c6ff52b900e3";
        public static Guid CommandSet = new Guid(CommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolbarGroup = 0x0001;
        public const int MusicMenuGroup = 0x0002;
        public const int FolderPickerGroup = 0x0003;
        public const int PlayPause = 0x0100;
        public const int VolumeUp = 0x0101;
        public const int VolumeDown = 0x0102;
        public const int PickFolder = 0x0103;
        public const int MusicMenu = 0x1001;
        public const int NextTrack = 0x0104;
        public const int PreviousTrack = 0x0105;
    }
}